language: node_js
node_js:
  - 8.3.0

addons:
  apt:
    packages:
      - curl
      - screen
  chrome: stable

env:
  - NODE_ENV=test

before_install:
  - npm install -g cordova ionic

before_script:

  # Create env files
  # TODO: create an npm script for this
  - cp src/environments/environment.sample.ts src/environments/environment.ts
  - cp src/environments/environment.sample.ts src/environments/environment.dev.ts

  # Generate locale files
  - npm run locales

  # Update the webdriver
  - npm run test:e2e:update

  # Use chromium which is installed by default on Travis
  - export CHROME_BIN=chromium-browser

  # Run in-memory display for the browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Fix permissions for screen
  - sudo mkdir -p /var/run/screen
  - sudo chmod 775 /var/run/screen

  # Run `ionic serve` in the background with screen
  - screen -dm ionic serve -b -d --address localhost --port 8100

  # Copy the `environment.sample.ts` as `environment.test.ts`
  - cp ./src/environments/environment.sample.ts ./src/environments/environment.test.ts

after_success:

  # Send test coverage report to coveralls
  - npm run test:coverage

notifications:
  slack:
    secure: pmbZJPzfN0v7g0/UL6jMh8qTe1SLQE1tb+BXytfU1xPzTRidfElVtsXR7s3P5Lku3akmmNOLCeVfumlCixYpVksFUje19lWpjbIFXovUaEdcah1/Ctmkt/b06qCpYh5is0uxygQRsfPP772C1Z7sxZMeeHi9q8Br22HInPfcuFBmibAn3AMhJH6Q7x1U/eTijnfdQB23+vCxE8j/dO6WQxEBho4/PgB0rG/A6Aqgz6mzPwy0zqkz8XB5CjSNMG1S2aHEETo6Keg428lmOn+zxzFqiFaQkQ0TsZf/QAMcY8+J7eLV/6DEi9LexKwTtsj5Cd08uYhMeaEQTyw6n+70nvdOLuxOBUaHasVgT3XAF+nh03ItWPXpx0dSbw6ZQ+xnWzyltyryfc6dMhy3LDYjg7O+mqG0/qNxdHUWd3MTV9lfjBO8Y2h6ZYX+WGbpYe8q9ZzXb6TUTtsz+6YFhdLbu0SN/4t678lMBrk5LVImnktxxnpJpzRumU5ywRphMLb9K8kL7hNt1Uq1FKoYEG+oirKuisF68XlONeKmtWPLW74b+ftr5tF9vC8Re84nt6Qnm56wtg6BQU98/vkTzyJVrpx9Ouh4Io2EqW3XbwnqWbAR52uwTABGgGGjqwRYLxlKUPT4A38KabEQ1Fa4bXd5eZCe5NKXciL5lnWNtt64PD0=
